line-length = 80
exclude = ["migrations", "tests/"]

# Aktivieren spezifischer Regelkategorien
# E: Pyflakes (Syntax-Fehler, undefinierte Namen, etc.)
# F: Flake8 (Standard-Python-Fehler)
# N: PEP 8 Namenskonventionen (z.B. CamelCase für Klassen, snake_case für Funktionen)
# I: Import-Check (unbenutzte Importe, Import-Reihenfolge)
select = ["E", "F", "N", "I"]

# Ignoriere spezifische Regeln, die nicht verwendet werden sollen
ignore = ["E203"]  # Ignoriere z. B. die Regel für zu lange Zeilen (E501)


