line-length = 110
exclude = ["migrations", "tests/"]

# Activating specific rule categories
# E: Pyflakes (syntax errors, undefined names, etc.)
# F: Flake8 (standard python errors)
# N: PEP 8 naming conventions (e.g., CamelCase for classes, snake_case for functions)
# I: Import-Check (unused imports, import order)
select = ["E", "F", "N", "I"]


