# Generated by Django 4.2.16 on 2024-10-14 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('access_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eduvmstore.role')),
            ],
        ),
        migrations.CreateModel(
            name='AppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
                ('instantiation_notice', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('public', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('fixed_ram_gb', models.FloatField()),
                ('fixed_disk_gb', models.FloatField()),
                ('fixed_cores', models.FloatField()),
                ('per_user_ram_gb', models.FloatField()),
                ('per_user_disk_gb', models.FloatField()),
                ('per_user_cores', models.FloatField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eduvmstore.user')),
            ],
        ),
    ]
