# Generated by Django 4.2.16 on 2024-10-16 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef978952-6008-4e04-a71b-c856061761f1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
