# Generated by Django 4.2.16 on 2024-10-16 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0002_user_deleted_at_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ac876a9-4c1b-4ed2-ac5e-6f0069c5d42c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
