# Generated by Django 4.2.16 on 2024-10-16 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptemplate',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('383324f3-2647-415a-a61a-9803a365cc18'), editable=False, primary_key=True, serialize=False),
        ),
    ]
