# Generated by Django 4.2.16 on 2024-10-16 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0004_alter_apptemplate_deleted_at_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b6a8e81-9a84-4b99-b336-a097d4c662eb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
