# Generated by Django 4.2.16 on 2024-10-16 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0005_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fb7c0130-7487-4675-b2fb-56ba7ae487de'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='AppTemplate',
            new_name='AppTemplates',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='users',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eduvmstore.roles'),
        ),
        migrations.AlterField(
            model_name='apptemplates',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eduvmstore.users'),
        ),
    ]
