# Generated by Django 4.2.16 on 2024-10-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0007_alter_users_id'),
        ('eduvmstore', '0007_users_is_active_alter_users_id'),
    ]

    operations = [
    ]
