# Generated by Django 4.2.16 on 2025-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0008_merge_20241026_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplates',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
