# Generated by Django 4.2.16 on 2025-03-18 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0011_apptemplateinstantiationattributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduvmstore.apptemplates')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduvmstore.users')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user_id', 'app_template_id'), name='unique_user_app_template', violation_error_message='User already has this app template in favorites'),
        ),
    ]
