# Generated by Django 4.2.16 on 2025-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0011_apptemplateinstantiationattributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplates',
            name='version',
        ),
    ]
