# Generated by Django 4.2.16 on 2025-03-19 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0012_favorites_favorites_unique_user_app_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplates',
            name='version',
        ),
        migrations.CreateModel(
            name='AppTemplateAccountAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('app_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_attributes', to='eduvmstore.apptemplates')),
            ],
        ),
    ]
