# Generated by Django 4.2.16 on 2025-03-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0013_remove_apptemplates_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplates',
            name='volume_size_gb',
            field=models.FloatField(null=True),
        ),
    ]
