# Generated by Django 4.2.16 on 2025-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0014_apptemplates_volume_size_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplates',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
