# Generated by Django 4.2.20 on 2025-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0016_alter_apptemplates_volume_size_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplates',
            name='ssh_user_requested',
            field=models.BooleanField(default=False),
        ),
    ]
