# Generated by Django 4.2.16 on 2025-04-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduvmstore', '0017_apptemplates_ssh_user_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplates',
            name='per_user_cores',
        ),
        migrations.RemoveField(
            model_name='apptemplates',
            name='per_user_disk_gb',
        ),
        migrations.RemoveField(
            model_name='apptemplates',
            name='per_user_ram_gb',
        ),
    ]
